name: "PROD DEPLOY"

on:
  push:
    branches:
      - main


jobs:
  terraform:
    # Permission can be added at job level or workflow level
    permissions:
      id-token: write
      contents: read

    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: arn:aws:iam::082877456478:role/github-actions-hscastro-pipeline
      aws-region: us-east-1
      aws-statefile-s3-bucket: hscastro-sa-east-1-terraform-statefile
      aws-lock-dynamodb-table: hscastro-sa-east-1-terraform-lock